FROM mcr.microsoft.com/dotnet/sdk:9.0.5 AS build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0.5
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "TaskManager.dll"]